---

- name: Copy Drupal installation scripts
  template:
    src: drupal{{ item }}_install.j2
    dest: /var/www/drupal{{ item }}_install.sh
    mode: 0755
  with_items:
    - 6
    - 7
    - 8
    - 8dev
  sudo: true

- name: Remove anything inside docroot before installing Drupal
  shell: rm -rf /var/www/site/docroot/*
  when: drupal_install
  sudo: true

- name: Install Drupal
  shell: /var/www/drupal{{ drupal_install_version }}_install.sh
  when: drupal_install
