---

- name: Copy Drupal installation scripts
  template:
    src: drupal{{ item }}_install.j2
    dest: /var/www/drupal{{ item }}_install.sh
  with_items:
    - 6
    - 7
    - 8
    - 8dev
  sudo: true

# TODO: Setting "mode" to 755 in the above template task appears to have no effect :(
- name: Set Drupal installation scripts to executable
  file: path=/var/www/drupal{{ item }}_install.sh mode=755
  with_items:
    - 6
    - 7
    - 8
    - 8dev
  sudo: true
