---

- name: setup main vhosts directory
  file: path="/var/www/vhosts" state=directory recurse=yes
  become: true

- name: set up docroot directory
  file: path="/var/www/vhosts/{{ item.directory }}/docroot" state=directory recurse=yes
  with_items: vlad_webserver_settings
  become: true

- name: set up docroot directory
  file: path="/var/www/vhosts/{{ item.directory }}/logs" state=directory recurse=yes
  with_items: vlad_webserver_settings
  become: true

# Include the appropriate OS specific setups.
- include: debian_apache.yml
  when: ansible_os_family == "Debian"

- include: debian_apache_ssl.yml
  when: ansible_os_family == "Debian"

#- include: redhat_apache.yml
#  when: ansible_os_family == "RedHat"

#- include: redhat_apache_ssl.yml
#  when: ansible_os_family == "RedHat"

# Run some common tasks.
- name: symlink www directory from home directory
  file: src="/var/www/vhosts" dest=/home/{{ user }}/www state=link force=yes

- name: set default login directory to be /var/www/vhosts
  lineinfile: dest=/home/{{ user }}/.bashrc state=present line='cd /var/www/vhosts'
  tags: apache2

- name: add www-data user to dialout group
  user: name=www-data groups=dialout append=yes
  become: true
