---

- name: Copy apotropaic .bash_prompt file
  copy:
    src: bash_prompt.sh
    dest: /home/{{ user }}/.bash_prompt
  when: bling_shell_prompt

- name: Enable apotropaic bash prompt
  lineinfile:
    dest: /home/{{ user }}/.bashrc
    line: '[[ -f "${HOME}/.bash_prompt" ]] && . "${HOME}/.bash_prompt"'
  when: bling_shell_prompt

- name: Enable bash prompt hints
  lineinfile:
    dest: /home/{{ user }}/.bashrc
    line: "export BLING_PS1_SHOW{{ item.source | upper }}='{{ item.enable | default('', true) }}';"
  with_items: "{{ bling_shell_prompt_hints }}"
  when: (bling_shell_prompt and item.source is defined)
