---
- name: Install Xdebug PHP component
  apt: pkg=php{{ php_version }}-xdebug state=installed
  register: xdebug_installed
  become: true

- name: Get first line of /etc/php/{{ php_version }}/mods-available/xdebug.ini
  command: head -n 1 /etc/php/{{ php_version }}/mods-available/xdebug.ini
  when: xdebug_installed.changed or xdebug_force_reconfigure == true
  register: xdebug_first_line
  become: true
  changed_when: false

- name: Update Xdebug configuration file
  template: src=php_apache2_xdebug.ini.j2 dest=/etc/php/{{ php_version }}/mods-available/xdebug.ini
  when: xdebug_installed.changed or xdebug_force_reconfigure == true
  become: true